name: Release
# only trigger on pull request closed events
on:
  push:
    tags:        
      - '*'  
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v3
      - name: Install Requirements
        run: |
          sudo apt update
          sudo snap install goreleaser --classic
          make dep-github-release
      - name: Releasing
        run: make github-release
  
  darwin:
    needs: linux
    runs-on: macos-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v3
      - name: Install Requirements
        run: |
          brew install goreleaser
          brew install gh
          brew install jq
          brew install wget
      - name: Releasing
        run: make github-release-darwin
  
  windows:
    needs: darwin
    runs-on: windows-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v3
      - name: Install Requirements
        shell: pwsh
        run: |
          Invoke-WebRequest "https://github.com/goreleaser/goreleaser/releases/download/v1.8.3/goreleaser_Windows_x86_64.zip" -o goreleaser.zip
          Expand-Archive goreleaser.zip
          Invoke-WebRequest "https://github.com/cli/cli/releases/download/v2.13.0/gh_2.13.0_windows_amd64.zip" -o gh.zip
          Expand-Archive gh.zip
          choco install make
      - name: Releasing
        run: make github-release-windows