on: [push, pull_request]
name: Test
jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
      - name: Install Requirements
        run: |
          go mod vendor
          go install golang.org/x/tools/cmd/goimports@latest
      - name: Checking
        run:  |
          golangci-lint cache clean
          make check
      - name: Build
        run: make build
  
  test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
      - name: Install Requirements
        run: |
          go mod vendor
          go install golang.org/x/tools/cmd/goimports@latest
      - name: Checking
        run:  |
          golangci-lint cache clean
          make check
      - name: Build
        run: make build
  
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
      - name: Install Requirements
        run: |
          choco install make
          go mod vendor
      - name: Checking
        run:  |
          set GO111MODULE=on
          golangci-lint cache clean
          make check-windows
      - name: Build
        run: make build-windows